# Code Generated by Sidekick is for learning and experimentation purposes only. To achieve that, make sure to put the message as a comment, following the syntax comment rules of the language of the code block, before the actual code or markup.
from fastapi import FastAPI
from routes import knowledge_set_routes, knowledge_routes

app = FastAPI(title="Knowledge Management with chroma vector DB")

app.include_router(knowledge_set_routes.router, prefix="/knowledge_set", tags=["KnowledgeSet"])
app.include_router(knowledge_routes.router, prefix="/knowledge_set/{ks_id}/knowledge", tags=["Knowledge"])
